### ISSUE TITLE
Would Table Component in PingCode Wiki be opensourced?

### ISSUE THREAD

**Issue by byoungd** [worktile/slate-angular#103]
Table Component in PingCode Wiki is really nice! 
Is it built with this repo and any plan for opensource?

**Comment by pubuzhixing8** [comment]
Yes, our table is built on slate-angular.  
We also plan to open source an out-of-the-box editor, the table is included, but this is a relatively complicated matter, and the specific date is uncertain.

**Comment by byoungd** [comment]
> Yes, our table is built on slate-angular. We also plan to open source an out-of-the-box editor, the table is included, but this is a relatively complicated matter, and the specific date is uncertain.

Any progress for the ` out-of-the-box editor`?
