### ISSUE TITLE
组件引入报错

### ISSUE THREAD

**Issue by MiniLebron** [worktile/slate-angular#149]
Angular版本为11.2
npm install slate-angular
app.module.ts引入
import { SlateModule } from 'slate-angular';
imports: [
        SlateModule,
   ],
然后就报了下面的错误

Error: ./node_modules/ngx-Quill/fesm2015/ngx-quill.mjs 1152:48-65
Can't import the named export 'ɵɵsanitizeHtml' from non EcmaScript module (only default export is available)

"angularCompilerOptions": {
        "enableIvy": true,
        "fullTemplateTypeCheck": true,
        "strictInjectionParameters": true
    }
ivy开启关闭都试过

**Comment by pubuzhixing8** [comment]
https://github.com/worktile/slate-angular/blob/master/README.zh-CN.md 我补充了使用文档 你可以先参照下 看看缺少什么步骤，并且你Issues中提的错误日志是 quill 抛出的错误跟 slate-angular 应该没有关系，你可以检查下，有问题再沟通 @MiniLebron
