### ISSUE TITLE
Transforms.moveNodes does not work

### ISSUE THREAD

**Issue by ilya2204** [worktile/slate-angular#150]
Hi, I'm trying to use the method `Transforms.moveNodes(this.editor, {at: [0], to: [1]}),` but it just removes node at destination path from the DOM, but it is still present in `editor.children` objects.

**Comment by ilya2204** [comment]
I noticed that if I comment out the logic for the first insert in packages / src / view / container.ts (lines 39-42) then the moveNodes method starts working, but the DOM gets weird.
![image](https://user-images.githubusercontent.com/52297646/144708757-1f7c88fa-4cfa-40d8-a47d-25c6c772a073.png)

**Comment by pubuzhixing8** [comment]
Thanks for your feedback @ilya2204 
I tried to fix this problem, you can try to see if it can solve your problem

**Comment by ilya2204** [comment]
@pubuzhixing8 Yes, thanks a lot, everything seems to work as it should
