### ISSUE TITLE
Getting the location of the current input

### ISSUE THREAD

**Issue by smnbbrv** [worktile/slate-angular#154]
Hi @pubuzhixing8 

thank you very much for the job you do! It saves others (like me) lots of time.

I faced an issue with implementing the link element:

```
<ng-template #link let-context="context" let-viewContext="viewContext">
    ...
      <button [contentEditable]="false" type="button" (click)="editLink(context.element, context, viewContext)">
        <fa-icon [icon]="editLinkIcon"></fa-icon>
      </button>
    ...
  </ng-template>
```

The code above is an adapted version of a react implementation of a link. The key point is `editLink(context.element, context, viewContext)`, where I put literally all what's known about the link at this moment, but still there is no information about the location of this element, that the `Transforms` can actually do its job. Ideally something like

```
    const newProperties = {
      url: 'new-url'
    } as Partial<Element>;

    Transforms.setNodes(this.editor, newProperties, { at: 'here-goes-location' });
```

would be perfect.

Looks like React editor has a corresponding method: https://github.com/ianstormtaylor/slate/issues/3627#issuecomment-632371795

Is there a way to find the location of the element? Or expose it e.g. as a part of the context? Or, maybe, there is a more valid and correct solution (which I will be very happy to adopt)?

**Comment by pubuzhixing8** [comment]
Sure, there are two cases

Case 1: Inside the custom component

like demo image component: 

```typescript
//...
export class DemoElementImageComponent extends BaseElementComponent<ImageElement> implements OnInit {
    ngOnInit(): void {
        const path = AngularEditor.findPath(this.editor, this.element);
        Transforms.setNodes(this.editor, newProperties, { at: path });
    }
}
```

Case 2: Not inside custom components

need get the path by the editor selection, like code：

```typescript
const linkEntry = Editor.above<Element>(this.editor, {
    at: this.editor.selection,
    match: n => Editor.isBlock(this.editor, n) && n.type === 'link',
    Transforms.setNodes(this.editor, newProperties, { at: path });
});
const path = linkEntry[1];
```

**Comment by pubuzhixing8** [comment]
@smnbbrv

**Comment by smnbbrv** [comment]
Thank you very much, this is exactly what I was looking for. I missed the image component demo because it was a block-alike and I thought I can have no info there, but I was wrong :)
