### ISSUE TITLE
Weird behavior with the android keyboard "Gboard"

### ISSUE THREAD

**Issue by RaulPROP** [worktile/slate-angular#194]
### Steps to reproduce

1. Go to [http://slate-angular.ngnice.com/images](http://slate-angular.ngnice.com/images), or any example that you want.
2. Focus the editor on any word by taping at it.
3. Double-tap the same word to select the range of the word.

### Expected behaviour

The word is selected with its range.

### Actual behaviour

Using the Gboard, the word gets duplicated and it is not range-selected, it just mantain the original selection of length 0.

### Additional information

1. This only happens on slate-angular. I could not reproduce it on slate.
2. It is reproducible on any Android browsers except firefox (but firefox also doesn't range-selects the word).
3. I tested it on iOS, and it works properly on any browser.

### Video reproducing the issue

https://user-images.githubusercontent.com/15218519/160141271-16b6cc5a-78d1-42b1-829a-144646cf47ce.mp4

**Comment by Benny739** [comment]
Any news on this one? 
Swipe to text on gboard also makes the editor go completely crazy.

**Comment by RaulPROP** [comment]
I reported the [same issue to lexical](https://github.com/facebook/lexical/issues/1716) and they were able to [fix it](https://github.com/facebook/lexical/pull/1732). As [one of them said](https://github.com/facebook/lexical/issues/1716#issuecomment-1099289222), the bug probably comes from the compositionstart event.

**Comment by RaulPROP** [comment]
There has been some pull requests [[1](https://github.com/ianstormtaylor/slate/pull/4988)], [[2](https://github.com/ianstormtaylor/slate/pull/5071)] on the `slate-react` package that solves most of the android issues.

I've tried to merge those changes into this package, but I have not achieve to make it work 100%.

I manage to solve the android issues, but then I somehow added some other bugs, some of them are: 
- on android, when pressing the enter, the text from the start of the paragraph to the cursor position gets duplicated.
- some examples don't work, probably because of the selection management.
- sometimes when pressing enter, the "can't resolve the DOM point" error emerges.

@pubuzhixing8 are you planning to merge those changes into this library?

**Comment by BitPhinix** [comment]
If you need help brining these changes to slate-angular I'd be happy to help out with any questions

**Comment by RaulPROP** [comment]
> If you need help brining these changes to slate-angular I'd be happy to help out with any questions

I opened the PR #210 . Your help would be more than welcome :)
