### ISSUE TITLE
Error occur while creating BlockCard

### ISSUE THREAD

**Issue by donaldxdonald** [worktile/slate-angular#199]
## Env
Angular: 13.2.0

## Background
I've set the `isBlockCard` of a block element to `true`. Then an ASSERTION ERROR was thrown at the init phase. It seems like it is an error of `createComponent` method in `descendant.component.ts`.

## Error
Console Error
![image](https://user-images.githubusercontent.com/29999387/164956007-df466675-5234-421f-8395-b0a63c66656a.png)

Assertion in Source Code
![image](https://user-images.githubusercontent.com/29999387/164956058-8cb62180-f822-404c-84cc-07375f726a9d.png)

## Additional information
![image](https://user-images.githubusercontent.com/29999387/164955949-92cad374-2b65-474f-a26e-bc429986d985.png)
So i guess it would be solved after removing the second and the third `null` arguments.

**Comment by pubuzhixing8** [comment]
感谢贡献，我可能会尽快升级 angular 13 尝试！

**Comment by donaldxdonald** [comment]
> 感谢贡献，我可能会尽快升级 angular 13 尝试！

我昨天尝试了下将 slate-angular 升级到 angular 13，发现一些实验性的 DOM API 不兼容了，因为 angular 13 匹配的 TS 4.4+ 已经不支持那些 API 了。又由于这个项目是照着 slate-react 来实现的，slate 那边的 TS 才 3.9.7，所以更新 angular 13 的话需要调整部分实现方式

**Comment by pubuzhixing8** [comment]
#203
