### ISSUE TITLE
编辑器中添加下拉多选/单选框该如何实现？

### ISSUE THREAD

**Issue by guimingfu** [worktile/slate-angular#201]
尝试在编辑器中添加一个下拉选择框，得到以下错误~
想实现的效果是向编辑器添加html表单元素（单选，复选，日期，数字输入框等）请问基于slate-angular该如何实现呢？

`import { ChangeDetectionStrategy, Component, HostListener } from '@angular/core';
import { SelectElement } from '../../../../custom-types';
import { BaseElementComponent } from 'slate-angular';

@Component({
    selector: 'span[demo-element-select]',
    template: `
    <div>
        <label>Label: </label>
        <select>
            <option>option 1</option>
            <option>option 2</option>
            <option>option 3</option>
        </select>
        <slate-children [children]="children" [context]="childrenContext" [viewContext]="viewContext"></slate-children>
    </div>
    `,
    host: {
        class: 'demo-element-select'
    },
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class DemoElementSelectComponent extends BaseElementComponent<SelectElement> {

    @HostListener('click', ['$event'])
    click(event: MouseEvent) {
        event.preventDefault();
    }
}`

![image](https://user-images.githubusercontent.com/21689494/168496727-3944a2f3-1cf3-46f0-91f5-60e38b3b2320.png)

**Comment by pubuzhixing8** [comment]
@guimingfu 可以尝试给出你的 Demo 地址，我来配合解决下

**Comment by guimingfu** [comment]
> @guimingfu 可以尝试给出你的 Demo 地址，我来配合解决下

Demo建好了，谢谢你的帮助！
https://stackblitz.com/edit/angular-ivy-ljc6gs?file=src/app/app.component.ts

**Comment by pubuzhixing8** [comment]
@guimingfu 这个应该是需要把 type === 'select' 的节点设置成 void 就可以了，渲染逻辑有些不同。

```
const withSelect = <T extends Editor>(editor: T) => {
  const { isVoid } = editor;

  editor.isVoid = (element: any) => {
    return element.type === 'select' || isVoid(element);
  };

  return editor;
};
```

使用的时候加上：

```
editor = withSelect(withHistory(withAngular(createEditor())));
```

https://stackblitz.com/edit/angular-ivy-8qbu3u?file=src%2Fapp%2Fapp.component.ts

**Comment by guimingfu** [comment]
> 

感谢你的回复。设置isVoid之后就变成Block元素了，我想这些输入控件是行内元素该如何实现呢？
类似于Wiki中日期选择的效果：
![image](https://user-images.githubusercontent.com/21689494/169684014-8305857e-93da-4788-a41b-730cd32b7b7c.png)

**Comment by pubuzhixing8** [comment]
slate 还有一个控制 inline 的可重写函数 isInline ，参考 [mention](https://github.com/worktile/slate-angular/blob/master/demo/app/mentions/mentions.component.ts) 的实现
