### ISSUE TITLE
怎么获取当前操作受影响的节点？

### ISSUE THREAD

**Issue by guimingfu** [worktile/slate-angular#205]
通过onKeydown的Backspace来控制删除逻辑，怎么获取待删除的节点信息来判断如果是**mention**就调用event.preventDefault();来阻止删除。

**Comment by guimingfu** [comment]
> 

观察dom结构发现mention节点后面还有一个span;
![image](https://user-images.githubusercontent.com/21689494/174261003-7f572ac8-e957-4cae-b38d-f2f54cf900b3.png)

通过下面代码可以实现，不知道有没其他方法?
`onKeydown = (event: KeyboardEvent) => {
        switch (event.key) {
            case 'Backspace':
                const { selection, operations } = this.editor;
                if (selection && Range.isCollapsed(selection)) {
                    const currentNode = Node.get(
                        this.editor,
                        [selection.focus.path[0], selection.focus.path[1] - 1]
                    ) as any;
                    if (currentNode.type === 'mention') { event.preventDefault(); }
                }
                break;
        }
    };`

**Comment by pubuzhixing8** [comment]
@guimingfu 思路应该就是这样，根据选区关联的节点判断， 就是 API 可以更简洁点
<img width="937" alt="截屏2022-06-21 15 36 52" src="https://user-images.githubusercontent.com/18631804/174743193-c4515e70-eeca-4571-9316-9ade6c1be3ec.png">
了
