### ISSUE TITLE
IME bug when typing after an inline element in Edge Browser

### ISSUE THREAD

**Issue by donaldxdonald** [worktile/slate-angular#219]
**Description**
When I finish typing Chinese after an inline element, the composition characters would not be deleted.

**Record**
![ezgif-1-8f7ce209b5](https://user-images.githubusercontent.com/29999387/201021790-308599e2-9f4e-40ae-8366-8afdad7e611a.gif)

**Environment**
Mac OS 13
Microsoft Edge 107.0.1418.35

**Comment by donaldxdonald** [comment]
I‘ve opened a PR to solved this issue. #220 
@pubuzhixing8

**Comment by pubuzhixing8** [comment]
@donaldxdonald Thanks
