### ISSUE TITLE
Support for Angular 15

### ISSUE THREAD

**Issue by Halanson** [worktile/slate-angular#221]
Angular 15 was released on November 16, 2022. Could you please provide an update for this library to support Angular 15 as well?

Thank you.

**Comment by pubuzhixing8** [comment]
We will support recently.

**Comment by Ashy6** [comment]
We have supported

**Comment by Halanson** [comment]
@pubuzhixing8 , why have you reopened this issue?

As far as I can see, there is a v15 on npmjs.com, but this repository does not have a git tag for v15.

**Comment by pubuzhixing8** [comment]
There was a problem in code build at that time, but it has been resolved now.
