### ISSUE TITLE
Slate angular doesn't scroll/keep focus on input text, instead the new input text is below the view.

### ISSUE THREAD

**Issue by shaylanger** [worktile/slate-angular#224]
Issue: When adding new text to the slate angular editor, if the text content exceeds the view (or browser window) the new text is typed below of the view, and in order to see the new text you must manually scroll down (and do this each time the text content goes out the bottom of the view) 

Expected: When the newly typed content goes outside of the view, the editor should automatially scroll to keep the cursor and new text in the view. 

This is a regression, as this behivour currently works on version: 1.6.3, and no longer works on version: 1.6.4

Here is a demo of the issue, were I have to scroll down to see the newly typed content:
![Kapture 2023-03-14 at 13 00 53](https://user-images.githubusercontent.com/25210667/225110266-a0b49888-133d-4175-9c8f-8c1bb7281046.gif)

from a quick look at commits, it looks like this was done intentionally to fix a table edge case issue: https://github.com/worktile/slate-angular/issues/144

Breaking commit: https://github.com/worktile/slate-angular/commit/2c96187a9e475208931d9b0b9ea2d3d4bd5fcd90

Can you please bring back scroll into view or some sort of functionallity that replicates it? This is a important feature of the editor to be able to keep the active content in the view.

**Comment by pubuzhixing8** [comment]
Thank you for your feedback.
I removed the `scrollIntoView` to resolve the issue of abnormal scrolling in the table plugin's focus. Currently, we are handling automatic scrolling at the editor level. Your suggestion is correct that slate-angular should include this feature. I intend to support this feature recently. @shaylanger

**Comment by shaylanger** [comment]
It looks like this issue was resolved in a revent merge: https://github.com/worktile/slate-angular/pull/230

Marking as closed as the feature works as intended.
