### ISSUE TITLE
Upgrade to latest angular and slatejs versions

### ISSUE THREAD

**Issue by dweggemans** [worktile/slate-angular#229]
Could you please upgrade this library to support the latest angular and slate versions? I've tried to provide a pull request, but ran into some issues that I don't know how to resolve.

Thanks!

**Comment by pubuzhixing8** [comment]
I intend to upgrade latest version of slate recently, but it could be a long time because there are too much version to study and synchronize.
We need to make sure that these commits are stable.
Upgrading Angular to 16 is more easy, we'll complete it soon.

**Comment by dweggemans** [comment]
Any news or timeframe on these upgrades?

**Comment by BenRacicot** [comment]
Hi, yes I noticed that my npm is demanding `slate-history@"^0.66.0"`

```
npm ERR! Could not resolve dependency:
npm ERR! peer slate-history@"^0.66.0" from slate-angular@16.0.0
```

Here is from the readme.
```
"dependencies": {
    "direction": "^1.0.3",
    "is-hotkey": "^0.1.6",
    "slate": "0.67.1",
    "slate-history": "0.66.0",
    "slate-angular": "1.6.5"
}
```

Also, is slate-angular usable with standalone components?
