### ISSUE TITLE
I'd like to help support and improve Slate-Angular

### ISSUE THREAD

**Issue by BenRacicot** [worktile/slate-angular#235]
Hello! I have a large project where I need to invest in a rich text editor and I really appreciate how you've approached SlateJS. 

Perhaps your stakeholders would allow me and my engineers to create PRs to bring Slate-Angular up to date with Slate and Angular's latest features?

### Regarding Standalone Angular Components

I have already converted the package to standalone Angular components and would like to create a PR for your team to review.

My entire app is standalone and must import standalone components. 
As you may know, standalone components are supported within modules. However, without standalone support developers like myself will not be able to use SlateJS.

I have refactored the package and demo app to fully standalone but would need permission on the repo to push.

There is an error regarding [packages/src/view/container-item.ts:78](https://github.com/worktile/slate-angular/blob/master/packages/src/view/container-item.ts#L78) that I would need help with.

```
ERROR TypeError: componentFactory.create is not a function
```

**Comment by why520crazy** [comment]
https://github.com/worktile/slate-angular/pull/236

**Comment by why520crazy** [comment]
@BenRacicot The master branch already supports standalone components.

How to reproduce the following errors？
```
ERROR TypeError: componentFactory.create is not a function
```

**Comment by pubuzhixing8** [comment]
@BenRacicot I am pleased to hear that you are using slate-angular. However, our team is upgrading to Angular 16 and will also support standalone. Any other PRs are welcome. I have invited you to this repo for write permission and look forward to your contributions. Good luck!

**Comment by BenRacicot** [comment]
That's excellent! Thanks so much for including me.
