### ISSUE TITLE
Unable to select paragraph with void element with triple-click

### ISSUE THREAD

**Issue by Bricklou** [worktile/slate-angular#244]
As the title explain it, the library doesn't act as expected with the triple click to select all the text in paragraph (all element and text combined). Maybe related to #180 and #186.

__Packages Versions:__
* `angular`: 15.2.10
* `slate`: ^0.100.0
* `slate-angular`: ^15.1.3

React slate behaviour from the official docs:

https://github.com/worktile/slate-angular/assets/15181236/adff3c0b-68d4-48a9-bd9c-2a8f11d92f3c

Angular slate behaviour from the official docs:

https://github.com/worktile/slate-angular/assets/15181236/26d05178-b065-4605-b5e1-d5e7b3cc105b

**Comment by pubuzhixing8** [comment]
Hi @Bricklou, I tried to resolve the problem of triple-click in pr #253, if you have any issue else, please tell me.
