### ISSUE TITLE
using ngModelChange triggers when clicking into not just content change

### ISSUE THREAD

**Issue by Jordan-Hall** [worktile/slate-angular#245]
Example: https://stackblitz.com/edit/angular-ivy-puuqev?file=src%2Fapp%2Fapp.component.ts,src%2Fpolyfills.ts,src%2Fapp%2Fapp.component.html

When you use debugger every click triggers change detection and value change rather than when the value just changes

**Comment by pubuzhixing8** [comment]
This should be resolved in PR https://github.com/worktile/slate-angular/pull/238
