### ISSUE TITLE
Custom element children not placed at the right position in component

### ISSUE THREAD

**Issue by Bricklou** [worktile/slate-angular#249]
I was looking at fixing my bug related to #244, i discovered that the zero-width space weren't at the right place like shown on this screen:
![image](https://github.com/worktile/slate-angular/assets/15181236/7eb31527-5b50-4ee0-a878-02d4cef8e7d1)

This code cause the behaviour below:
https://github.com/worktile/slate-angular/assets/15181236/167b8721-5f73-4e08-8e0c-945d6c21cfc4

EDIT: another side effect of using ZWS is that we can't select the whole paragraph (it seems slate-react have some kind of fix related to this issue)

**Comment by pubuzhixing8** [comment]
I reproduced this problem locally. I will confirm the problem. Thanks for the feedback.
