### ISSUE TITLE
Confused by setup instructions

### ISSUE THREAD

**Issue by aeslinger0** [worktile/slate-angular#254]
I'm trying to use slate-angular for the first time and following the instructions on the home page. I'm confused why "Add Text Mark" step has us include `<slate-leaves [context]="context" [viewContext]="viewContext" [viewContext]="viewContext"></slate-leaves>` as the template, but in your demo the template is blank. Also, why is `[viewContext]="viewContext"` in there twice?

**Comment by pubuzhixing8** [comment]
If you use 16.1.0-next.0 and later versions, you do not need to add `<slate-leaves [context]="context" [viewContext]="viewContext" [viewContext]="viewContext"></slate-leaves >`, `[viewContext]="viewContext"` Assigning value twice is a low-level error.
We have made some architectural improvements in version 16.1.0-next.0 to improve the rendering performance of slate-angular. One of the changes is that custom text components and custom element components no longer need to add `<slate- leaves [context]="context" [viewContext]="viewContext"></slate-leaves>` and `<slate-children [children]="children" [context]="childrenContext" [viewContext]="viewContext" ></slate-children>` component, I will update the README document and corresponding Demo later. Thank you for your feedback.

**Comment by gmcdowell-soleran** [comment]
@pubuzhixing8 I'm trying to update to the latest version, but this part seems to confuse me as well. Is there now no means to define where in the template the children outlet goes? Is the expectation now to have a component for each HTML element?
