### ISSUE TITLE
firefox 全选，直接输入拼音，异常

### ISSUE THREAD

**Issue by wangfupeng1988** [worktile/slate-angular#91]
mac OS firefox v89 访问 http://slate-angular.ngnice.com/
聚焦编辑器，cmd + a 全选，然后直接输入拼音，一直输入不成功。

---------------

PS：我也在基于 slate 搞编辑器，也遇到了 firefox （还有 safari ，但我看你们 safari 没问题）的这种全选、输入拼音的坑。如果你们有好的解决方案的话，欢迎回复分享一下。我最近也在持续优化、修改 bug 中。thx ～
![image](https://user-images.githubusercontent.com/9583120/124348676-df183500-dc1d-11eb-8c64-d747f5b556a7.png)

**Comment by pubuzhixing8** [comment]
@wangfupeng1988   
slate-angular refers to   [https://github.com/worktile/slate-angular/blob/fdf2959732eea39ff5bda9ede001653411cae13c/packages/src/components/editable/editable.component.ts#L656](https://github.com/worktile/slate-angular/blob/fdf2959732eea39ff5bda9ede001653411cae13c/packages/src/components/editable/editable.component.ts#L656)  
slate-react 最新版本已经解决了这个问题，可以升级尝试（placeholder可能有影响，可以隐藏）  
当前 slate-angular firefox 中全选后输入不成功属于另外一个问题，全选时选区映射出错，需要修复~~

**Comment by wangfupeng1988** [comment]
@pubuzhixing8 多谢，我们去试试～
